### PR TITLE
Prevent in-source builds

### PR DESCRIPTION
**Pull request by friendlyanon**
Related: https://github.com/veselink1/refl-cpp/pull/47#discussion_r606757953

### CODE REVIEW

**Comment by veselink1** [comment]
Great! I might tweak the message a bit.

**Comment by friendlyanon** [comment]
What would you like to see in the message?

**Comment by veselink1** [comment]
```
FATAL: In-source builds are not supported.

Make a new directory (e.g., 'build/'), and run CMake from there.  You may
need to delete 'CMakeCache.txt' and 'CMakeFiles/'.
```
This. 

I will change it and merge this PR in a bit.

**Comment by veselink1** [comment]
Unintentionally merged this before the refactor in #46 !

**Comment by friendlyanon** [comment]
That PR already does out-of-source builds :)

**Pull request merged**
